trunk-version = "^0.21.1"

[build]
# minify assets on release build
minify = "on_release"
# use `cargo update` to update cargo lockfile
locked = true

# the versions are specified here to get reproducible builds, make sure to
# bump the versions of these tools occasionally.
[tools]
wasm_opt = "version_123"
wasm_bindgen = "0.2.95"
tailwindcss = "3.4.17"
